# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'ChatAppExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatAppExercise

  target 'ChatAppExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppExerciseUITests' do
    # Pods for testing
  end
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  # for Analytics without IDFA collection capability

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
